### PR TITLE
Port Nova Storm BuruBuru from GearHead 1

### PR DESCRIPTION
**Pull request by AmkG**
Also drawing.  The drawing could probably use some more work.  I am not sure if the Storm Pistols are OP enough.

### CODE REVIEW

**Comment by jwvhewitt** [comment]
I was thinking about porting the Nova Storm earlier, but I may change the weapon options a little.

**Comment by jwvhewitt** [comment]
And now the Storm Pistols have linked fire.
GHC_NovaStorm

**Comment by AmkG** [comment]
So I was looking at the code as well, and wow.

See, in GearHead 1, mount points were at a premium, because your end goal was a -1MV -1TR flying Savin with 6 Phase Cannons sniping everyone from the first turn, and in the mean time stocking up on long-range powerful weapons was how you got there.

In GearHead Caramel (so far), I actually devalue mount points a little, because you don't really need more than one Phase Cannon or Laser Cannon or Shaka Cannon (well you might put a spare Shaka Cannon in case of running out of ammo during long fights but putting an alternate weapon for situational use was a viable option as well, such as a Blast N missile).  That sometimes meant doing stuff like stripping off collar mount points and installing small weapons in the arms, because mount points are an extra 0.5 tons of weight and you have to shave off excess weight for better mobility.

But Linked Fire upends that.  I am now thinking of designing, say, a Zerosaiko with several mount points loaded down with as many Storm Pistols (or other Linked Fire weapons when they appear) as I can fit to serve as an assault mech.  Imagine a Zerosaiko with 6 Storm Pistols doing Linked Fire to decimate the enemy (sure that's 7 Me, but that would be worth it and I can specialize a lancemate with high Ego and Concentration).

The nice thing is that I still want to keep my charging melee mech and my artillery mech arechetypes.  The Me price for a mass-linked-fire assault mech can get quite steep and of course there is a chance of missing shots always, so I still need mechs to be useful even when running out of mana.  So the combat strategy would be something like, my charging melee mechs charge into battle twice (trying to reach the support/artillery of the enemy), or charge-then-melee, my assault mechs move to optimal range and unleash all their linked fire, then my artillery mechs mop up and destroy any remaining opponents.  After my assault mechs run out of mana, they switch to near-range support.

**Comment by AmkG** [comment]
Just got a mech with 4x Storm Pistols and wow, it's fun.  Not as OP as I expected, especially with the very high Me cost, but one thing I notice with Linked Fire is that if you focus all 4x Storm Pistols on a single enemy it gets overwhelmed very quickly, getting Overwhelmed: +12 from a single Linked Fire action, which is useful against e.g. Chameleons with their >70 Mobility.  This seems fine to me due to the high Me cost (and possibly battery? I have 4x on a Nove Storm with a MP-1350 engine, it seems to work well with the size 9 Power Source, whatever that does).  So its role as an assault/pin down mecha certainly seems cemented.

**Pull request merged**
