### PR TITLE
Implement Encourage action for Negotiation skill

### PR DESCRIPTION
**Pull request by AmkG**
Closes: #62

### CODE REVIEW

**Comment by jwvhewitt** [comment]
Merging. Maybe this should tie to Performance, instead? Another skill use I am planning to give to Negotiation is Intimidation; use it on enemy mecha to make them eject (if badly damaged) or cause some other effect (burn Stamina? combat penalty?).

**Comment by AmkG** [comment]
Could tie to Performance, and renamed to "Inspire" instead.  There seems to be an overlap with the two, so maybe we can try to hash out what the differences are, thematically?

So here's some thought.  Negotiation is about convincing others about something, whereas Performance is flashy showmanship.

So, thematically, we can consider Negotiation as "reliable, but minimal" effect, whereas Performance is about "risky, but impactful" effect.

* Negotiation = manager (reliable, but minimal)
* Performance = pop star (risky, but impactful)

So Encourage, which is reliable but gives a measly 2->5 MP to a single target, seems to tie better to Negotiation.

Performance might instead get STARSTRUCK!, which targets a large area around the caster and makes everyone nearby run around like starstruck fanpeople (like haywire but a distinct status effect? meh.... how about skipping one move from their next turn?), but which can be resisted by Concentration + Ego.

What do you think?

Also skills usage needs to `dole_experience`.

**Comment by jwvhewitt** [comment]
Here's an idea: give Performance a "Listen to my Song!" ability that has random effects within a certain radius. Maybe it'll pump up your allies. Maybe it'll demoralize your enemies. Maybe, if you screw the roll badly enough, it'll have the opposite effect. 
image

**Comment by jwvhewitt** [comment]
All of these abilities can also be used by enemies against the player character. Enemy pilots who know how to sing are pretty rare, but should be memorable.

**Comment by jwvhewitt** [comment]
If I add that, the only two skills without a mecha combat use will be Wildcraft and Science. "Take Cover" could be moved to Wildcraft, potentially. "Spot Weakness" could be moved to Science.

**Pull request merged**
