### PR TITLE
Can now purchase direct at the cyberdoc terminal

### PR DESCRIPTION
**Pull request by AmkG**

### CODE REVIEW

**Comment by AmkG** [comment]
Note that unlike normal shops, this cyberdoc terminal will sell all available cyberware.  I'm still figuring out how to make it more like a normal shop.

**Comment by AmkG** [comment]
Screenshot from 2020-05-05 03-30-29
Screenshot from 2020-05-05 03-32-03
Screenshot from 2020-05-05 03-32-06

**Comment by AmkG** [comment]
The cyberdoc can now be sourced from a shop!

If the cyberdoc terminal is not given a shop at construction it defaults to showing all cyberware.  Later we can probably remove this and make it so that the cyberdoc will not have any wares if it has no attached shop, but for now this is useful when tweaking the trauma balance etc., just set the wujung hospital `cybershop` to `None` so you can see all the cyberware.  Later when `shop` is `None` the cyberdoc will not sell anything but can install what you have in your inventory and remove cyberware.

**Comment by Zireael07** [comment]
What does "Optical Spine" do? That's a fairly strangle piece of cyberware...

**Comment by AmkG** [comment]
Instead of organic nerves in your spine, they are replaced with fiber optic cables.

Maybe better renamed to fiber optic spine?

**Comment by AmkG** [comment]
```
SpineCyberware
    name = "Optical Spine"
    desc = "Replaces many of the spinal nerves with fiber-optic data transmission wires."
    statline = { Speed = 3, Reflexes = 1, Knowledge = 2, Body = -2 }
    scale = HumanScale
    shop_tags = ("CYBERWARE",)
    faction_list = (None,)
```

**Comment by Zireael07** [comment]
I think a rename would be better - optical spine sounds like you can suddenly see with it. Fiber optic spine reflects what it's doing much better.

**Comment by AmkG** [comment]
Optical Spine has been around since GH1 and also makes an appearance in GH2, but I agree a rename would be better.

**Comment by AmkG** [comment]
And now there's a random NPC near the cyberdoc terminal to tell you about it.

**Pull request merged**
