### PR TITLE
Champions first cut

### PR DESCRIPTION
**Pull request by AmkG**
First cut at creating a function that creates champions.

No missions that involve them yet, but you can look at what champions could be produced via the mecha editor, select the new "Edit Mecha Champion" entry.

### CODE REVIEW

**Comment by AmkG** [comment]
Added one possible objective in the "falling star" where you come upon 4 champion mecha and fight them.  Not sure if it's done properly.  Still playtesting, have not encountered the scenario yet.

**Comment by jwvhewitt** [comment]
You can find it easier if you turn on dev_mode in the configuration file and set the label to LABEL = "DZRE_TEST" in one of the roadedge propp missions that use the falling star objective. Start a new game and you'll be able to jump straight to that mission from the mecha hangar.

**Comment by AmkG** [comment]
I got this from a `Launcher` that was modified by the champion upgrader to include a `BurnAttack`.  What's strange is that the normal basic attack completed.


```
Traceback (most recent call last):
  File "main.py", line 271, in <module>
    play_the_game()
  File "main.py", line 262, in play_the_game
    action(tsrd)
  File "main.py", line 145, in start_game
    game.start_campaign(egg)
  File "/home/almkglor/games/gearhead-caramel/game/__init__.py", line 24, in start_campaign
    camp.play()
  File "/home/almkglor/games/gearhead-caramel/gears/__init__.py", line 424, in play
    super(GearHeadCampaign, self).play()
  File "/home/almkglor/games/gearhead-caramel/pbge/campaign.py", line 107, in play
    exp.go()
  File "/home/almkglor/games/gearhead-caramel/game/exploration.py", line 433, in go
    self.camp.fight.go(self)
  File "/home/almkglor/games/gearhead-caramel/game/combat/__init__.py", line 329, in go
    self.do_combat_turn( chara )
  File "/home/almkglor/games/gearhead-caramel/game/combat/__init__.py", line 312, in do_combat_turn
    chara_ai.act(self.camp)
  File "/home/almkglor/games/gearhead-caramel/game/combat/aibrain.py", line 240, in act
    self.attempt_attack(camp)
  File "/home/almkglor/games/gearhead-caramel/game/combat/aibrain.py", line 169, in attempt_attack
    self.minr,self.midr,self.maxr = self.get_min_mid_max_range(self.npc.get_attack_library())
  File "/home/almkglor/games/gearhead-caramel/gears/base.py", line 358, in get_attack_library
    p_list = geffects.InvoLibraryShelf(p, p.get_attacks())
  File "/home/almkglor/games/gearhead-caramel/gears/base.py", line 2268, in get_attacks
    my_invos.append(self.get_multi_attack(max(ammo.quantity - ammo.spent, 2), 9))
  File "/home/almkglor/games/gearhead-caramel/gears/base.py", line 2252, in get_multi_attack
    aa.modify_basic_attack(self, ba)
  File "/home/almkglor/games/gearhead-caramel/gears/attackattributes.py", line 73, in modify_basic_attack
    attack.fx.children.append(geffects.AddEnchantment(geffects.Burning,))
AttributeError: 'tuple' object has no attribute 'append'

```

**Comment by AmkG** [comment]
Looks like because `AttackRoll` initializes `self.children` with a proper `list`:

https://github.com/jwvhewitt/gearhead-caramel/blob/1dc64fc3324d81bcb905a1b6e49f78ea48cdc150/gears/geffects.py#L491

But `MultiAttackRoll` does not use a proper `list`, it gets the argument, which can be a tuple, which does not have the same interface as a `list`:

https://github.com/jwvhewitt/gearhead-caramel/blob/1dc64fc3324d81bcb905a1b6e49f78ea48cdc150/gears/geffects.py#L561-L564

I'll go through all the effects and check the proper initialization of `children` in all the effects.

**Comment by AmkG** [comment]
Okay, fixed the latent bug and consistently used `list` for sub-effects.

**Comment by AmkG** [comment]
The champions objective seems to work properly.  I'm okay with merging this in.  I think you're doing some extensive changes to the plot system, so I'll insert some kind of 1v1 champion battle maybe after you've merged in the new plot system.

**Pull request merged**
