### PR TITLE
Cyberware

### PR DESCRIPTION
**Pull request by AmkG**
Initial cut at implementing cyberware #78 

Need to implement the Cyberdoc Terminal, probably by refactoring `MechEngTerminal` and feeding the player character instead of some mecha, then go check what bugs pop up in the gear editor.

### CODE REVIEW

**Comment by AmkG** [comment]
Okay, so I have been debugging a good bit as well.

The gear editor is a bad interface for installing cyberware.  The main issue is that purchased personal-level items are put in your character inventory, but the gear editor can only install from the stash.  You have to first remove the cyberware from the character inventory before you can install it, LOL.  It's adequate but can be greatly improved.

Missing stuff as of now as well is:

* Installed cyberware in the gear editor need to display their details as well (Location, Trauma, bonuses/penalties).

Oh and gaining and removing skills from Cyberware works!

**Comment by AmkG** [comment]
Added cyberware info to the character info panel in fieldhq.

Screenshot from 2020-05-03 10-08-12

Skills you naturally have that you lost due to cyberware are listed in (parenthesis).  Notice that skills everyone has, that you lost due to cyberware, are also listed, such as (Close Combat) above which was lost due to Hand Dexterity Muscles (though skills everyone has that you have not lost will remain unlisted).  Skills you gained due to cyberware are listed with +plus.

Stats modified by cyberware have + or -.  + means it was improved by cyberware; - if it was degraded by cyberware; the number shown is the final total.

People without cyberware will not notice changes in the field hq except for the new "Cyberware: None" list.

Reusing the gear editor for cyberdoc is ***very*** unsatisfying.  I'll make a new UI.  For now, gear editor is adequate, so I'm marking this as ready for review/merge unless there are specific changes requested.

**Comment by AmkG** [comment]
New Cyberdoc UI done!

Screenshot from 2020-05-03 22-58-31

Screenshot from 2020-05-03 23-00-47

This pull request is "complete". modulo minor things like explaining the new cyberware mechanics, and possibly giving a lifepath where a character gets a random cyberware.

**Comment by AmkG** [comment]
If we decide to add a separate Cybertech skill, we can modify `max_trauma`, eg:

```python
    @property
    def max_trauma(self):
        if not stats.Cybertech in self.statline:
            return 0
        return (self.statline[stats.Body] // 3) + self.statline[stats.Cybertech]
```

**Comment by AmkG** [comment]
The `_CyberwareInstaller` class can be reused for selecting cyberware randomly for near-death experiences in backstory or in-story events.   It's given two functions, `alert` and `choose`, which are normally used for player interaction, but which can be virtualized.  `alert` is called when some failure to install occurs, so the random-cyberware-selection can do stuff like up Cybertech level or Body or select an alternate cyberware, and `choose` is called when the installation has multiple choices, so the random-cyberware-selection can select any of them except the last, which is always "[Cancel]".

**Comment by jwvhewitt** [comment]
How about if your character's Trauma score is subtracted from their Max Stamina? Cybered characters may be more deadly, but they also have to finish combat faster or run the risk of getting exhausted as their body is pushed beyond human endurance. I think this is an interesting trade-off, and though it is less severe than GH1/GH2 cyberdisfunctions, it mirrors the fact that heavily cybered characters have trouble with long expeditions.

**Comment by AmkG** [comment]
That's certainly a possibility.  Do we keep the existing max Trauma limit (`max_trauma = statline[Body]`) as well?  Or make the `max_trauma` equal to half the base max stamina (`max_trauma = ((5 + statline[Body] + statline[Ego]) // 2) // 2`, not include `Athletics`)?  I don't want to make the max Trauma modifiable by the cyberware themselves.

Do we support removing cyberware?  Or this is an irrevocable commitment?

**Comment by jwvhewitt** [comment]
I like the idea of adding a Cyberware skill; this would open the doors for lancemates who can get cyberware.

**Comment by AmkG** [comment]
>I like the idea of adding a Cyberware skill; this would open the doors for lancemates who can get cyberware.

If we're going to gate cyberware with some character-creation event, why not an Extropian tag or badge? (What's the difference between tag and badge?)

Maybe something like this:

* Extropian - you can have more than one cyberware.
* Classicist - no cyberware at all, other bonuses TBD.  Shrine tour?
* neither - up to one cyberware.

**Comment by jwvhewitt** [comment]
Tags just describe a character. Badges are earned through life events, and may affect reaction scores or have other effects. For instance, a character with the Soldier badge gets a +10 reaction score from NPCs with the Military tag. So an Extropian badge that can be earned through character creation or a near death experience would work.

The big difference between it being a badge and a skill is whether or not increasing your cyber-potential is an ongoing thing, or if you reach your full potential right after crossing the rubicon. I'm still leaning towards this being a skill instead of a badge since cybering up sounds more like a core character concept than an incidental detail.

**Comment by AmkG** [comment]
I'd probably have to remove High-capacity Heart if we subtract trauma from stamina: it has a trauma of 7 and subtracts one Body, so its +3 Athletics would end up giving 2.5 stamina on average, a measly sum that you can probably get more easily by adding raw points in Athletics.  And probably remove/reduce some of the -Body modifiers on most of the cyberware as well.

**Comment by AmkG** [comment]
> Badges are earned through life events, and may affect reaction scores or have other effects. For instance, a character with the Soldier badge gets a +10 reaction score from NPCs with the Military tag. So an Extropian badge that can be earned through character creation or a near death experience would work.

Ah, okay.  Maybe near-death experience can be one of two things:

* "A freak mecha whose control systems went out of control accidentally attacked you.  You suffered significant damage to your [location]; fortunately a [philanthropic/heroic/evangelical] extropian cyberdoc installed [cyberware] for free and taught you the benefits of cyberization." -> free cyberware, Extropian badge
* "A freak mecha whose control systems went out of control accidentally attacked you.  You suffered significant damage to your [location]; fortunately a [philanthropic/heroic/evangelical] [spirit guide/sage/monk] guided you through the healing process, which made you stronger than before you got a second chance." -> free +2 to random stat, Classicist badge

**Comment by jwvhewitt** [comment]
How is the trauma calculated? I think there should probably be a trauma-to-stat-point conversion rate, say 1 trauma point to 2 skill/stat points. I also think that the stat/skill bonuses should take the highest positive + highest negative, rather than being a sum, because otherwise it would be too easy to create unbeatable characters.

I also think cyberware should be removable in this game. That sounds more fun, and it will prevent players from getting locked into bad choices or feeling like they need to plan out their ideal cyber loadout right from the beginning.

**Comment by AmkG** [comment]
https://github.com/AmkG/gearhead-caramel/blob/37f609f058c255c2d8d6e4a0f3325d7d07dbad00/gears/base.py#L2558-L2570

Note that some cyberware disable skills by giving them -99, preventing the skill from being used ever.  Making trauma scale to do will make those cyberware unuseable.  Unless you think removing skills is somehow unfun, but if you can remove cyberware the player can just remove such cyberware, and it might be a good tradeoff for a focused character, e.g. Grappler Reconfiguration.

**Comment by jwvhewitt** [comment]
In this case, I think removing skills is not a great thing. In previous GH games, every character could take a wide variety of skills. In GHC, the skills you start with define your character to a large degree. So most characters are not likely to have the skills being penalized, so there really isn't any penalty.

**Comment by AmkG** [comment]
> I also think that the stat/skill bonuses should take the highest positive + highest negative, rather than being a sum, because otherwise it would be too easy to create unbeatable characters.

Unfortunately this is not how item-based stat bonuses tend to work in other games; implementing this would require explaining the mechanic to the player.

**Comment by jwvhewitt** [comment]
I think it's pretty standard in RPGs these days; D&D has had this rule since at least 3rd edition. Anyhow, we just need to make it clear that bonuses don't stack when a new piece is being installed.

**Comment by AmkG** [comment]
Given that cyberware is purchased separately before being installed, and cyberware is pricey, we need to show that even before purchase, not installation.

**Comment by AmkG** [comment]
Rebased, cyberware can now be removed.

**Comment by jwvhewitt** [comment]
Maybe cyberware could be purchased directly from the cyberdoc interface? I had planned to add store purchases to the mecha engineering part source list; this could also solve the issue of players buying cyberware they don't have the trauma capacity to install.

**Comment by AmkG** [comment]
> Maybe cyberware could be purchased directly from the cyberdoc interface? I had planned to add store purchases to the mecha engineering part source list; this could also solve the issue of players buying cyberware they don't have the trauma capacity to install.

What happens to removed cyberware?  They get destroyed?  Sold?

**Comment by AmkG** [comment]
> In this case, I think removing skills is not a great thing. In previous GH games, every character could take a wide variety of skills. In GHC, the skills you start with define your character to a large degree. So most characters are not likely to have the skills being penalized, so there really isn't any penalty.

How about brain reconfigurations that remove a skill everyone has (so it's always a penalty)?

```
ForebrainCyberware
    name = "Grappler Reconfiguration"
    statline = { MechaFighting = 2, CloseCombat = 2, MechaGunnery = -99, RangedCombat = -99 }

BrainstemCyberware
    name = "Spinal Pilot Link"
    desc = "Reconnects your self-defense reflexes to a special link to a mecha, sacrificing personal-scale combat for mecha-scale improvements."
    statline = { MechaPiloting = 2, Dodge = -99 }
```

Maybe Predator Reflexes can -99 Concentration.

**Comment by jwvhewitt** [comment]
Removed cyberware can be transferred to the stash, or placed in the inventory of the person who had it.

I still don't see the appeal of large skill penalties. If an upgrade gave -99 to Mecha Gunnery, I'd give it to a close combat specialist.

**Comment by AmkG** [comment]
> Removed cyberware can be transferred to the stash, or placed in the inventory of the person who had it.

Mildly complicates installing --- the `Available` list has to show items in the inventory and stash *and* being sold at the cyberdoc.

Also I noticed personal-scale items cannot be stashed, only dropped (which appears to destroy them forever).

How do I persist the set of items being sold, a la shops?  Do waypoints in `ghwaypoints` get persisted in the save file?  How do I rotate items once a day?

**Comment by AmkG** [comment]
> I still don't see the appeal of large skill penalties. If an upgrade gave -99 to Mecha Gunnery, I'd give it to a close combat specialist.

"I still don't see the appeal of small stat penalties.  If an upgrade gave -2 to Body, I'd give it to a mecha pilot specialist."

It's just more of the same thing cyberware already does?

**Comment by AmkG** [comment]
Cyberware now gives stamina loss, and we show this visually in the cyberdoc:

Screenshot from 2020-05-04 18-41-17

Hovering over a cyberware suggests stamina loss as well, though not very much --- See "Trauma/Sta":

Screenshot from 2020-05-04 18-46-23

Note that you can lose more stamina than your trauma, but only as a consequence of loss to Body, Ego, or Athletics.  The cyberdoc will give you the absolute loss of stamina, including due to body/ego/athletics penalties.

**Comment by jwvhewitt** [comment]
I think what bothers me most about the -99 skill modifiers is the difference between trading off between two things you want and choosing a dump stat. Trade offs are interesting when there's a tension between what you lose and what you stand to gain. Anyhow, I would prefer to hold off on such an extreme penalty unless it were needed for balance reasons.

**Comment by jwvhewitt** [comment]
Wow, you did a lot of work on this. It looks great!

**Pull request merged**
